### ISSUE TITLE
TYPO3 v9 LTS compatibility

### ISSUE THREAD

**Issue by AKaravas** [ervaude/fs_code_snippet#10]
I would like to know if you are planning to update the extension to be compatible with TYPO3 v9 LTS.

I tried to do it myself to help a bit but this is a list of problems i encountered: 
1. I installed the extension on TYPO3 v9.5.5 and the first error that i had, is that it couldnt find the Constant **MODE_MIXED**. For this, i had to comment out the lines 29 and 30 on TCA/Overrides/tt_content.php and include the Static template. Then i commented them  both in and it worked.
2. The second problem i got and it drove me nuts was this error: **Fatal error: Declaration of DanielGoerz\FsCodeSnippet\Form\Element\CodeSnippetElement::render() must be compatible with TYPO3\CMS\T3editor\Form\Element\T3editorElement::render(): array in /home/someLink/someMoreLink/anotherLink/updateExtensions/htdocs/typo3conf/ext/fs_code_snippet/Classes/Form/Element/CodeSnippetElement.php on line 25**

This is where i said "ok, let me ask if he plans to update it, because i can not find the reason why this happening". 

Best regards

**Comment by ervaude** [comment]
Hi,
yes. I will release a compatible version. I just don't know when. You can use the 9-compat Branch in the meantime. The version in the branch will work with 9LTS but it is not "good enough" for a release yet.

To require the 9-compat Branch with composer you have to add the GitHub Repository in your composer.json as a repository.

Hope this helps!

**Comment by AKaravas** [comment]
would you mind to explain the not "good enough"? What is to be optimized? We might be able to help a bit

**Comment by ervaude** [comment]
I'd like to integrate with the ckeditor in the backend so that you have syntax highlightning there as well. Until v8 this was build on top of the t3editor which is ... suboptimal and breaks in v9 as you have noticed, too.

Currently the extension just uses the t3editor without any modification which I find a step backwards.

Anyway I push my latest cleanups so you can have a look at the current status.

**Comment by ervaude** [comment]
Today I finally released a 2.0 version that (only) supports TYPO3 9 LTS
