### ISSUE TITLE
TYPO3 v8 LTS compability

### ISSUE THREAD

**Issue by christen90** [ervaude/fs_code_snippet#3]
I updated my typo3 and now in version 8.7.0 LTS Code Snippets aren't working.

**Comment by ervaude** [comment]
Currently only TYPO3 8.6 is supported. I will release a new version for 8 LTS soon.

**Comment by ervaude** [comment]
Can you elaborate what exactly is "not working"? In my 8 LTS the snippets are rendered just fine.

I will raise the dependecy in composer.json and ext_emconf.php so the extension can be installed in 8 LTS but I don't see any prolem with the actual content elements?

So if you have any issues other than the installation process, please let me know.

**Comment by christen90** [comment]
Sorry. My fault. The Update just kicked the fluid_styled_content inclusion.
