### ISSUE TITLE
Displayed several times

### ISSUE THREAD

**Issue by e-LUNATIC** [ervaude/fs_code_snippet#5]
If i add more than 1 code element on a page there only shows the first multiple times.

**Comment by ervaude** [comment]
What TYPO3 version are you using?

**Comment by e-LUNATIC** [comment]
7.16 with php 7.0

**Comment by ervaude** [comment]
Sorry, I cannot confirm that. The extension runs fine in TYPO3 7.6.16 as you can see at https://usetypo3.com ;)

Are you using fluid_styled_content? Please check your TypoScript inclusions, clear your caches and check for other extensions that might interfere with content rendering.

**Comment by e-LUNATIC** [comment]
yes, using fluid_styled_content. i will check other conflicts.

**Comment by ervaude** [comment]
Strange. Your example looks like the three code snippet content elements actually contain the same content in the bodytext field. Can you check in your backend and database?

**Comment by ervaude** [comment]
Cannot tell much more without a backend access.

**Comment by e-LUNATIC** [comment]
really strange. In the backend everything is normal.
https://ollinet.org/fileadmin/unbenannt.jpg

**Comment by ervaude** [comment]
Hmm now I am curious :)
Do you have some kind of caching in place? Like a varnish or nc_stticfilecache that maybe delivers an old version of the page? If you delete the last code snippet, does it disappear from the frontend? And if you create a new one with one line - does it get the wrong content again?

**Comment by ervaude** [comment]
Also can you flush all caches in the install tool?

**Comment by e-LUNATIC** [comment]
nc_staticfilecache is deactivated. I have flushed all caches several times also before i open this issue. I have delete the last element and it disappear from frontend. But if i add a new one, regardless which it contains it shows the first.

**Comment by e-LUNATIC** [comment]
i have the issue!!!!!
The problem is the extension min
https://typo3.org/extensions/repository/view/min
Deactivate and everything is perfect!
Please excuse me and thank you for your time and help!

**Comment by ervaude** [comment]
OK, I'll have a look at that at the weekend maybe there is a bug in the extension that can be fixed.

On a sitenote: I use the extension sourceopt for minifying the HTML output and I use gulp to create a minified frontend build that I include then with TYPO3 without any compression during execution time.

I'm glad you got it working. Closing the issue though.
