### ISSUE TITLE
composer require fails

### ISSUE THREAD

**Issue by t3easy** [ervaude/fs_code_snippet#6]
You defined typo3/cms-core >=7.6.0,>=8.7.0 as dependency.
The comma (,) will be treated as a logical AND.
https://getcomposer.org/doc/articles/versions.md#range

You have to use double pipe (||).

<details>
composer require danielgoerz/fs-code-snippet
Using version ^1.8 for danielgoerz/fs-code-snippet     
./composer.json has been updated
Loading composer repositories with package information                                                                                                                       Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for danielgoerz/fs-code-snippet ^1.8 -> satisfiable by danielgoerz/fs-code-snippet[1.8.0].
    - danielgoerz/fs-code-snippet 1.8.0 requires typo3/cms-core >=7.6.0,>=8.7.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
</details>

**Comment by ervaude** [comment]
Oops, gonna fix that real quick.

Thanks for reporting

**Comment by t3easy** [comment]
PR is in ;)

**Comment by ervaude** [comment]
Thank you, solved by PR #7

**Comment by t3easy** [comment]
Thank you for fixing on sunday!

**Comment by ervaude** [comment]
No problem, this was a nobrainer though :)

Please try again with 1.8.1

**Comment by t3easy** [comment]
Works as expected ;) Nobrainer or nightmare thanks!
