### ISSUE TITLE
indend code

### ISSUE THREAD

**Issue by thombeck** [ervaude/fs_code_snippet#8]
Hi
I can't get space with your extensin so I lost the indentation of code in front end. In backend is fine.
Can you help me ?
Thanks

**Comment by ervaude** [comment]
Can you describe a little bit more in detail what you are doing and provide an example.
What TYPO3 version are you using?

Just a wild guess, but do you maybe use an extension for HTML minification that removes the spaces in the frontend?

**Comment by thombeck** [comment]
Yes that's it !
I use min extension. I overriden the conf and my code is ident.
Thanks for your help !
